# Tell Mongoid which environment this configuration is for.
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true
development:
  sessions:
    default:
      hosts:
        - 127.0.0.1:27017
      database: webrucker_development
      options:
        raise_not_found_error: false
test:
  sessions:
    default:
      hosts:
        - 127.0.0.1:27017
      database: webrucker_test
options:
  raise_not_found_error: false