# Tell Mongoid which environment this configuration is for.
production:
  sessions:
    default:
      uri: URI.parse(ENV['MONGOHQ_URL'])
development:
  sessions:
    default:
      hosts:
        - 127.0.0.1:27017
      database: webrucker_development
test:
  sessions:
    default:
      hosts:
        - 127.0.0.1:27017
      database: webrucker_test